# The URL the site will be built for
base_url = "/"

title = "inthemainfra.me"
description = "notes/rants"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true
minify_html = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

# https://github.com/guppy0130/archie-zola
theme = "archie-zola"

[slugify]
paths_keep_dates=true

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
# Put all your custom variables here
mode = "toggle"
copyright = "guppy0130"

[[extra.translations.en]]
show_more = "read more ⟶"
previous_page = "←"
next_page = "→"
posted_on = "on "
posted_by = "published by"
read_time = "minute read"
menus = [
  { name = "posts", url = "/posts", weight = 2 },
]
