---
# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/github-workflow.json
name: Deploy

on:
  push:
    tags:

jobs:
  build_and_deploy_site:
    name: Build and deploy Jekyll site
    runs-on: ubuntu-latest
    env:
      JEKYLL_ENV: production
    steps:
      - name: Get dependencies
        run: |-
          sudo apt-get update
          sudo apt-get -y install ffmpeg parallel
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: "setup ruby"
        uses: "ruby/setup-ruby@v1"
        with:
          ruby-version: "3.1"
          bundler-cache: true
      - name: jekyll action
        uses: limjh16/jekyll-action-ts@v2
        with:
          enable_cache: true
      - name: make images videos
        run: make images videos
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: _site
          path: _site
          if-no-files-found: error # this should always upload something
      - name: Deploy
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-args: "--prod --confirm"
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-project-name: website
          alias-domains: yanglang.now.sh
          working-directory: _site
          github-comment: false
